apiVersion: v1
kind: Pod
metadata:
  name: pikachu-pod
  namespace: pokeland
spec:
  containers:
  - name: pokeland-nginx
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: pokeland-redis
    image: redis:latest
    ports:
    - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
