apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: database-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: web-server
        image: nginx:latest
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 15; rm -f /tmp/healthy; sleep 600
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

