apiVersion: v1
kind: Service
metadata:
  name: nginx-ns2-clusterip-svc
  labels:
    app: nginx-ns2
  namespace: namespace-2
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-ns2
  type: ClusterIP
