apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    app: nginx-ns1
  name: nginx-ns1
  namespace: namespace-1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-ns1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-ns1
    spec:
      containers:
      - image: nginx:1.26.2
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
