apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-svc
  labels:
    app: nginx-deployment
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx-deployment
  type: LoadBalancer
